import 'package:flutter/material.dart';
class AppColors {
  AppColors._();

  static const white = Color(0xFFffffff);
  static const black = Color(0xFF000000);
  static const assets = Color(0xff51267D);
  static const background = Color(0xFFF8F6FA);
  static const red = Color(0xffFF3B30);
  static const assets50 = Color(0xff7B4D9C);
  static const green = Color(0xff4CD964);
  static const lightGrey = Color(0xffE7E9E8);
  static const baseText = Color(0xff818C99);
  static const unselectedBottomNavItem = Color(0xff818C99);
  static const grey = Color(0xffABABAB);
  static const baseText50 = Color(0xffABABAB);
  static const baseButton = Color(0xffF2F3F5);
  static const unableButton = Color(0xff818C99);
  static const baseButtonIcon = Color(0xff818C99);
  static const productTableBackground = Color(0xffFBFBFD);
  static const unselectedTabBar = Color(0xffE2F2FF);
  static const inactive = Color(0xffeeeeee);
  static const divider = Color(0xffF2F2F2);
  static const lightRed = Color(0x33FF3B30);
  static const darkGrey = Color(0xFF818C99);
  static const productBackground = Color(0xFFEEE9F2);
  static const assets005 = Color.fromRGBO(81, 38, 125, 0.05);
  static const c = Color(0xffCCCCCC);
  static const black2 = Color(0xff818C99);
  static const mainColor2 = Color(0xff0E0D23);
  static const dividerColor = Color.fromRGBO(4, 4, 21, 0.08);
  static const black1 = Color(0xff040415);
  static const color1 = Color(0xff1A1A1A);
  static const black05 = Color.fromRGBO(0, 0, 0, 0.05);
  static const black86 = Color(0xff868686);
  static const black16 = Color(0xff161616);
  static const myOrdersTabBackground = Color(0xffEFEFF4);
  static const lightTestGrey = Color(0xffEBEDF0);
  static const chooseReasonComment = Color(0xffF2F2F2);
}